name: Build All Dockerfiles

on:
  push:
    branches:
      - main

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Dockerfiles
        id: set-matrix
        run: |
          # Find directories containing Dockerfile
          dirs=$(find . -type f -name Dockerfile -exec dirname {} \;)
          # Convert to JSON array
          json=$(jq -nc --arg dirs "$dirs" '$dirs | split("\n") | map(select(length > 0))')
          echo "Found directories:"
          echo "$json"
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Remove ./ prefix
          tag=$(basename "${{ matrix.dir }}")
          echo "Building image for ${{ matrix.dir }} with tag $tag"
          docker build "${{ matrix.dir }}" -t "myregistry/${tag}:latest"
